kind: Deployment
apiVersion: apps/v1
metadata:
  name: toy-robot-frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: toy-robot
      role: frontend
      env: production
  template:
    metadata:
      name: frontend
      labels:
        app: toy-robot
        role: frontend
        env: production
    spec:
      containers:
      - name: frontend
        image: gcr.io/cloud-solutions-images/toy-robot:1.0.0
        imagePullPolicy: Always
        command: ["bash", "-c", "gunicorn -b :8080 main:app"]
        ports:
        - name: frontend
          containerPort: 8080
        env:
          - name: API_KEY
            value: "bfe81c13-713d-4f59-8b7c-2e234494e0cd"