kind: Deployment
apiVersion: apps/v1
metadata:
  name: toy-robot-cli
spec:
  replicas: 3
  selector:
    matchLabels:
      app: toy-robot
      role: cli
      env: production
  template:
    metadata:
      name: cli
      labels:
        app: toy-robot
        role: cli
        env: production
    spec:
      containers:
      - name: cli
        image: gcr.io/cloud-solutions-images/toy-robot:1.0.0
        imagePullPolicy: Always
        volumeMounts:
          - mountPath: "/etc/secrets"
            name: secrets
            readOnly: true
        command: ["sh", "-c", "export API_KEY=$(cat /etc/secrets/API_KEY)\ncd app/\ngunicorn -b :8080 main:app"]
        ports:
        - name: cli
          containerPort: 8080
      volumes:
        - name: secrets
          secret:
            secretName: toy-robot-secrets